[#ftl]

[#-- Resources --]
[#-- At the moment, the condition resource types are being     --]
[#-- generated by prepending "waf" to the condition type       --]
[#-- If they end up needing custom attributes, then individual --]
[#-- reousrce type definitions will be needed here but for now --]
[#-- AWs hasn't defined any of interest                        --]
[#assign AWS_WAFV2_RULE_RESOURCE_TYPE = "wafv2Rule" ]
[#assign AWS_WAFV2_ACL_RESOURCE_TYPE = "wafv2Acl" ]
[#assign AWS_WAFV2_ACL_ASSOCIATION_RESOURCE_TYPE = "wafv2Assoc" ]
[#assign AWS_WAFV2_IPSET_RESOURCE_TYPE = "wafv2IpSet" ]
[#assign AWS_WAFV2_REGEX_PATTERN_SET_RESOURCE_TYPE = "wafv2RegexPatternSet" ]


[#-- Capture the variability between the various conditions --]
[#function getWAFConditionSetMappings conditionType ]
    [#switch conditionType]

        [#case WAF_IP_MATCH_CONDITION_TYPE]
            [#return
                {
                    "ResourceType" : {
                        "hamlet": AWS_WAFV2_IPSET_RESOURCE_TYPE,
                        "cfn": "AWS::WAFv2::IPSet"
                    }
                }
            ]
            [#break]

        [#case WAF_REGEX_MATCH_CONDITION_TYPE]
            [#return
                {
                    "ResourceType": {
                        "hamlet": AWS_WAFV2_REGEX_PATTERN_SET_RESOURCE_TYPE,
                        "cfn": "AWS::WAFv2::RegexPatternSet"
                    }
                }
            ]
            [#break]

        [#case WAF_GEO_MATCH_CONDITION_TYPE]
        [#case WAF_SIZE_CONSTRAINT_CONDITION_TYPE]
        [#case WAF_SQL_INJECTION_MATCH_CONDITION_TYPE]
        [#case WAF_BYTE_MATCH_CONDITION_TYPE]
        [#case WAF_XSS_MATCH_CONDITION_TYPE]
        [#case WAF_LABEL_MATCH_CONDITION_TYPE]
            [#return
                {
                    "ResourceType" : {}
                }
            ]
            [#break]
    [/#switch]

    [@fatal
        message="Invalid WAF Condition Type"
        context={
            "Type": conditionType
        }
    /]
    [#return
        {
            "ResourceType" : {}
        }
    ]
[/#function]

[#list [
    AWS_WAFV2_RULE_RESOURCE_TYPE,
    AWS_WAFV2_ACL_RESOURCE_TYPE,
    AWS_WAFV2_ACL_ASSOCIATION_RESOURCE_TYPE,
    AWS_WAFV2_IPSET_RESOURCE_TYPE,
    AWS_WAFV2_REGEX_PATTERN_SET_RESOURCE_TYPE ] as resource]

    [@addServiceResource
        provider=AWS_PROVIDER
        service=AWS_WEB_APPLICATION_FIREWALL_SERVICE
        resource=resource
    /]
[/#list]

[#list [
        AWS_WAFV2_IPSET_RESOURCE_TYPE,
        AWS_WAFV2_REGEX_PATTERN_SET_RESOURCE_TYPE
    ] as wafV2matchSetResourceType ]

    [@addOutputMapping
        provider=AWS_PROVIDER
        resourceType=wafV2matchSetResourceType
        mappings={
            REFERENCE_ATTRIBUTE_TYPE : {
                "UseRef" : true
            },
            ARN_ATTRIBUTE_TYPE : {
                "Attribute" : "Arn"
            }
        }
    /]
[/#list]

[#function formatDependentWAFConditionId type resourceId extensions...]
    [#local matchSetResourceType = (getWAFConditionSetMappings(type)["ResourceType"]["hamlet"])!"" ]
    [#return
        formatDependentResourceId(
            matchSetResourceType?has_content?then(
                matchSetResourceType,
                "HamletFatal: NoMatch found for SetMapping ${type}:"
            ),
            resourceId,
            extensions
        )
    ]
[/#function]

[#function formatDependentWAFRuleId resourceId extensions...]
    [#return formatDependentResourceId(
            AWS_WAFV2_RULE_RESOURCE_TYPE,
            resourceId,
            extensions)]
[/#function]

[#function formatDependentWAFAclId resourceId extensions...]
    [#return formatDependentResourceId(
            AWS_WAFV2_ACL_RESOURCE_TYPE
            resourceId,
            extensions)]
[/#function]

[#function formatDependentWAFAclAssociationId resourceId extensions...]
    [#return formatDependentResourceId(
        AWS_WAFV2_ACL_ASSOCIATION_RESOURCE_TYPE
        resourceId,
        extensions
    )]
[/#function]
