[#ftl]

[@addModule
    name="aws_service_log_db"
    description="Creates an Athena database of logs generated by AWS Services"
    provider=AWS_PROVIDER
    properties=[]
/]

[#macro aws_module_aws_service_log_db ]
    [@loadModule
        blueprint={
            "Tiers": {
                "ana": {
                    "Components": {
                        "aws_service_log_store": {
                            "Type": "objectsql",
                            "deployment:Unit": "aws-service-logs",
                            "Encryted": true
                        },
                        "aws_service_logs": {
                            "Type": "datacatalog",
                            "Description": "Data catalog of aws service logs which are saved to s3",
                            "deployment:Unit": "aws-service-logs",
                            "Tables" : {
                                "cloudfront_access_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        },
                                        "Prefix": "CLOUDFRONTLogs/"
                                    },
                                    "Layout": {
                                        "Columns": {
                                            "date": {
                                                "Type": "date"
                                            },
                                            "time": {
                                                "Type": "string"
                                            },
                                            "location": {
                                                "Type": "string"
                                            },
                                            "bytes": {
                                                "Type": "bigint"
                                            },
                                            "request_ip": {
                                                "Type": "string"
                                            },
                                            "method" : {
                                                "Type": "string"
                                            },
                                            "host": {
                                                "Type": "string"
                                            },
                                            "uri": {
                                                "Type": "string"
                                            },
                                            "status": {
                                                "Type": "int"
                                            },
                                            "referrer": {
                                                "Type": "string"
                                            },
                                            "user_agent": {
                                                "Type": "string"
                                            },
                                            "query_string": {
                                                "Type": "string"
                                            },
                                            "cookie": {
                                                "Type": "string"
                                            },
                                            "result_type": {
                                                "Type": "string"
                                            },
                                            "request_id": {
                                                "Type": "string"
                                            },
                                            "host_header": {
                                                "Type": "string"
                                            },
                                            "request_protocol":{
                                                "Type": "string"
                                            },
                                            "request_bytes": {
                                                "Type": "bigint"
                                            },
                                            "time_taken": {
                                                "Type": "float"
                                            },
                                            "xforwarded_for" :{
                                                "Type": "string"
                                            },
                                            "ssl_protocol": {
                                                "Type": "string"
                                            },
                                            "ssl_cipher": {
                                                "Type": "string"
                                            },
                                            "response_result_type": {
                                                "Type": "string"
                                            },
                                            "http_version" : {
                                                "Type": "string"
                                            },
                                            "fle_status": {
                                                "Type": "string"
                                            },
                                            "fle_encrypted_fileds": {
                                                "Type": "int"
                                            },
                                            "c_port": {
                                                "Type": "int"
                                            },
                                            "time_to_first_byte": {
                                                "Type": "float"
                                            },
                                            "x_edge_detailed_result_type": {
                                                "Type" : "string"
                                            },
                                            "sc_content_type": {
                                                "Type": "string"
                                            },
                                            "sc_content_len": {
                                                "Type": "bigint"
                                            },
                                            "sc_range_start": {
                                                "Type": "bigint"
                                            },
                                            "sc_range_end": {
                                                "Type": "bigint"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
                                            "Parameters" : {
                                                "field.delim": {
                                                    "Value" : "\t"
                                                },
                                                "skip.header.line.count" : {
                                                    "Value": 2
                                                }
                                            }
                                        }
                                    }
                                },
                                "alb_access_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Settings": {
                                        "SERVICE_NAME" :{
                                            "Value": "elasticloadbalancing"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_awslogs_location" ],
                                    "Layout": {
                                        "Columns": {
                                            "type": {
                                                "Type": "string"
                                            },
                                            "time": {
                                                "Type": "string"
                                            },
                                            "elb": {
                                                "Type": "string"
                                            },
                                            "client_ip": {
                                                "Type": "string"
                                            },
                                            "client_port": {
                                                "Type": "int"
                                            },
                                            "target_ip": {
                                                "Type": "string"
                                            },
                                            "target_port": {
                                                "Type": "int"
                                            },
                                            "request_processing_time": {
                                                "Type": "double"
                                            },
                                            "target_processing_time": {
                                                "Type": "double"
                                            },
                                            "response_processing_time": {
                                                "Type" : "double"
                                            },
                                            "elb_status_code": {
                                                "Type": "int"
                                            },
                                            "target_status_code" : {
                                                "Type": "string"
                                            },
                                            "received_bytes": {
                                                "Type": "bigint"
                                            },
                                            "sent_bytes": {
                                                "Type": "bigint"
                                            },
                                            "request_verb" : {
                                                "Type": "string"
                                            },
                                            "request_url" :{
                                                "Type": "string"
                                            },
                                            "request_proto": {
                                                "Type": "string"
                                            },
                                            "user_agent": {
                                                "Type": "string"
                                            },
                                            "ssl_cipher": {
                                                "Type": "string"
                                            },
                                            "ssl_protocol": {
                                                "Type": "string"
                                            },
                                            "target_group_arn": {
                                                "Type": "string"
                                            },
                                            "trace_id": {
                                                "Type": "string"
                                            },
                                            "domain_name": {
                                                "Type": "string"
                                            },
                                            "chosen_cert_arn": {
                                                "Type": "string"
                                            },
                                            "matched_rule_priority": {
                                                "Type": "string"
                                            },
                                            "request_creation_time": {
                                                "Type": "string"
                                            },
                                            "actions_executed": {
                                                "Type": "string"
                                            },
                                            "redirect_url": {
                                                "Type": "string"
                                            },
                                            "lambda_error_reason": {
                                                "Type": "string"
                                            },
                                            "target_port_list": {
                                                "Type": "string"
                                            },
                                            "target_status_code_list": {
                                                "Type": "string"
                                            },
                                            "classification": {
                                                "Type": "string"
                                            },
                                            "classification_reason": {
                                                "Type": "string"
                                            },
                                            "conn_trace_id": {
                                                "Type": "string"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.apache.hadoop.hive.serde2.RegexSerDe",
                                            "Parameters" : {
                                                "serialization.format": {
                                                    "Value" : "1"
                                                },
                                                "input.regex" : {
                                                    "Value": r'([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*)[:-]([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-.0-9]*) (|[-0-9]*) (-|[-0-9]*) ([-0-9]*) ([-0-9]*) \"([^ ]*) (.*) (- |[^ ]*)\" \"([^\"]*)\" ([A-Z0-9-_]+) ([A-Za-z0-9.-]*) ([^ ]*) \"([^\"]*)\" \"([^\"]*)\" \"([^\"]*)\" ([-.0-9]*) ([^ ]*) \"([^\"]*)\" \"([^\"]*)\" \"([^ ]*)\" \"([^\s]+?)\" \"([^\s]+)\" \"([^ ]*)\" \"([^ ]*)\" ?([^ ]*)?'
                                                }
                                            }
                                        }
                                    }
                                },
                                "nlb_access_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Settings": {
                                        "SERVICE_NAME" :{
                                            "Value": "elasticloadbalancing"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_awslogs_location" ],
                                    "Layout": {
                                        "Columns": {
                                            "type": {
                                                "Type": "string"
                                            },
                                            "version": {
                                                "Type": "string"
                                            },
                                            "time": {
                                                "Type": "string"
                                            },
                                            "elb" : {
                                                "Type": "string"
                                            },
                                            "listener_id": {
                                                "Type" : "string"
                                            },
                                            "client_ip": {
                                                "Type": "string"
                                            },
                                            "client_port": {
                                                "Type": "int"
                                            },
                                            "target_ip": {
                                                "Type": "string"
                                            },
                                            "target_port": {
                                                "Type": "int"
                                            },
                                            "tcp_connection_time_ms": {
                                                "Type": "double"
                                            },
                                            "tls_handshake_time_ms" :{
                                                "Type": "double"
                                            },
                                            "received_bytes" :{
                                                "Type": "bigint"
                                            },
                                            "sent_bytes": {
                                                "Type": "bigint"
                                            },
                                            "incoming_tls_alert": {
                                                "Type": "int"
                                            },
                                            "cert_arn" :{
                                                "Type": "string"
                                            },
                                            "certificate_serial": {
                                                "Type": "string"
                                            },
                                            "tls_cipher_suite": {
                                                "Type": "string"
                                            },
                                            "tls_protocol_version": {
                                                "Type": "string"
                                            },
                                            "tls_named_group": {
                                                "Type": "string"
                                            },
                                            "domain_name": {
                                                "Type": "string"
                                            },
                                            "alpn_fe_protocol": {
                                                "Type": "string"
                                            },
                                            "alpn_be_protocol": {
                                                "Type": "string"
                                            },
                                            "alpn_client_preference_list": {
                                                "Type": "string"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.apache.hadoop.hive.serde2.RegexSerDe",
                                            "Parameters" : {
                                                "serialization.format": {
                                                    "Value" : "1"
                                                },
                                                "input.regex" : {
                                                    "Value": r'([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*):([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-0-9]*) ([-0-9]*) ([-0-9]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*)$'
                                                }
                                            }
                                        }
                                    }
                                },
                                "classic_lb_access_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Settings": {
                                        "SERVICE_NAME" :{
                                            "Value": "elasticloadbalancing"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_awslogs_location" ],
                                    "Layout": {
                                        "Columns": {
                                            "timestamp": {
                                                "Type": "string"
                                            },
                                            "elb_name": {
                                                "Type": "string"
                                            },
                                            "request_ip": {
                                                "Type": "string"
                                            },
                                            "request_port": {
                                                "Type": "int"
                                            },
                                            "backend_ip": {
                                                "Type": "string"
                                            },
                                            "backend_port": {
                                                "Type": "int"
                                            },
                                            "request_processing_time": {
                                                "Type": "double"
                                            },
                                            "backend_processing_time": {
                                                "Type": "double"
                                            },
                                            "client_response_time" :{
                                                "Type": "double"
                                            },
                                            "elb_response_code" :{
                                                "Type": "string"
                                            },
                                            "backend_response_code": {
                                                "Type": "string"
                                            },
                                            "received_bytes" :{
                                                "Type": "bigint"
                                            },
                                            "sent_bytes": {
                                                "Type": "bigint"
                                            },
                                            "request_verb": {
                                                "Type": "string"
                                            },
                                            "url" : {
                                                "Type": "string"
                                            },
                                            "protocol": {
                                                "Type": "string"
                                            },
                                            "user_agent": {
                                                "Type": "string"
                                            },
                                            "ssl_cipher": {
                                                "Type": "string"
                                            },
                                            "ssl_protocol": {
                                                "Type": "string"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.apache.hadoop.hive.serde2.RegexSerDe",
                                            "Parameters" : {
                                                "serialization.format": {
                                                    "Value" : "1"
                                                },
                                                "input.regex" : {
                                                    "Value": r'([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*)[:-]([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-.0-9]*) (|[-0-9]*) (-|[-0-9]*) ([-0-9]*) ([-0-9]*) \\\"([^ ]*) ([^ ]*) (- |[^ ]*)\\\" (\"[^\"]*\") ([A-Z0-9-]+) ([A-Za-z0-9.-]*)$'
                                                }
                                            }
                                        }
                                    }
                                },
                                "waf_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        },
                                        "Prefix": "WAF/"
                                    },
                                    "Layout": {
                                        "Columns": {
                                            "timestamp": {
                                                "Type": "bigint"
                                            },
                                            "formatversion": {
                                                "Type": "int"
                                            },
                                            "webaclid": {
                                                "Type": "string"
                                            },
                                            "terminatingruleid": {
                                                "Type": "string"
                                            },
                                            "terminatingruletype": {
                                                "Type": "string"
                                            },
                                            "action": {
                                                "Type": "string"
                                            },
                                            "terminatingrulematchdetails": {
                                                "Type": "array<struct<conditiontype:string,location:string,matcheddata:array<string>>>"
                                            },
                                            "httpsourcename": {
                                                "Type": "string"
                                            },
                                            "httpsourceid": {
                                                "Type": "string"
                                            },
                                            "rulegrouplist": {
                                                "Type": "array<struct<rulegroupid:string,terminatingrule:struct<ruleid:string,action:string,rulematchdetails:string>,nonterminatingmatchingrules:array<string>,excludedrules:string>>"
                                            },
                                            "ratebasedrulelist": {
                                                "Type": "array<struct<ratebasedruleid:string,limitkey:string,maxrateallowed:int>>"
                                            },
                                            "nonterminatingmatchingrules": {
                                                "Type": "array<struct<ruleid:string,action:string>>"
                                            },
                                            "requestheadersinserted": {
                                                "Type": "string"
                                            },
                                            "responsecodesent": {
                                                "Type": "string"
                                            },
                                            "httprequest": {
                                                "Type": "struct<clientip:string,country:string,headers:array<struct<name:string,value:string>>,uri:string,args:string,httpversion:string,httpmethod:string,requestid:string>"
                                            },
                                            "labels": {
                                                "Type": "array<struct<name:string>>"
                                            },
                                            "captcharesponse": {
                                                "Type": "struct<responsecode:string,solvetimestamp:string,failureReason:string>"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.openx.data.jsonserde.JsonSerDe"
                                        }
                                    }
                                },
                                "vpc_flow_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Settings": {
                                        "SERVICE_NAME" :{
                                            "Value": "vpcflowlogs"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_awslogs_location" ],
                                    "Parameters": {
                                        "skip.header.line.count" : {
                                            "Value": 1
                                        }
                                    },
                                    "Layout": {
                                        "Columns": {
                                            "version": {
                                                "Type" : "int"
                                            },
                                            "account_id": {
                                                "Type": "string"
                                            },
                                            "interface_id": {
                                                "Type": "string"
                                            },
                                            "srcaddr": {
                                                "Type": "string"
                                            },
                                            "dstaddr": {
                                                "Type": "string"
                                            },
                                            "srcport": {
                                                "Type": "int"
                                            },
                                            "dstport": {
                                                "Type": "int"
                                            },
                                            "protocol": {
                                                "Type": "bigint"
                                            },
                                            "packets": {
                                                "Type": "bigint"
                                            },
                                            "bytes": {
                                                "Type": "bigint"
                                            },
                                            "start": {
                                                "Type": "bigint"
                                            },
                                            "end": {
                                                "Type": "bigint"
                                            },
                                            "action" :{
                                                "Type": "string"
                                            },
                                            "log_status": {
                                                "Type": "string"
                                            },
                                            "vpc_id": {
                                                "Type": "string"
                                            },
                                            "subnet_id": {
                                                "Type": "string"
                                            },
                                            "instance_id": {
                                                "Type": "string"
                                            },
                                            "tcp_flags": {
                                                "Type": "int"
                                            },
                                            "type": {
                                                "Type": "string"
                                            },
                                            "pkt_srcaddr": {
                                                "Type": "string"
                                            },
                                            "pkt_dstaddr": {
                                                "Type": "string"
                                            },
                                            "region": {
                                                "Type": "string"
                                            },
                                            "az_id": {
                                                "Type": "string"
                                            },
                                            "sublocation_type": {
                                                "Type": "string"
                                            },
                                            "sublocation_id": {
                                                "Type": "string"
                                            },
                                            "pkt_src_aws_service": {
                                                "Type": "string"
                                            },
                                            "pkt_dst_aws_service": {
                                                "Type": "string"
                                            },
                                            "flow_direction": {
                                                "Type": "string"
                                            },
                                            "traffic_path": {
                                                "Type": "string"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
                                            "Parameters" : {
                                                "field.delim": {
                                                    "Value" : " "
                                                }
                                            }
                                        }
                                    }
                                },
                                "dns_resolver_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_aws_dnsresolver_location" ],
                                    "Layout": {
                                        "Columns": {
                                            "version": {
                                                "Type": "string"
                                            },
                                            "account_id": {
                                                "Type": "string"
                                            },
                                            "region": {
                                                "Type": "string"
                                            },
                                            "vpc_id": {
                                                "Type": "string"
                                            },
                                            "query_timestamp": {
                                                "Type": "string"
                                            },
                                            "query_name": {
                                                "Type": "string"
                                            },
                                            "query_type": {
                                                "Type": "string"
                                            },
                                            "query_class": {
                                                "Type": "string"
                                            },
                                            "rcode": {
                                                "Type": "string"
                                            },
                                            "answers": {
                                                "Type": "array<struct<Rdata:string,Type:string,Class:string>>"
                                            },
                                            "srcaddr": {
                                                "Type": "string"
                                            },
                                            "srcport": {
                                                "Type": "int"
                                            },
                                            "transport": {
                                                "Type": "string"
                                            },
                                            "srcids": {
                                                "Type": "struct<instance:string,resolver_endpoint:string>"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.openx.data.jsonserde.JsonSerDe"
                                        }
                                    }
                                },
                                "network_firewall_logs": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        }
                                    },
                                    "Extensions" : [ "_datacatalog_aws_networkfirewall_location" ],
                                    "Layout": {
                                        "Columns": {
                                            "firewall_name": {
                                                "Type": "string"
                                            },
                                            "availability_zone": {
                                                "Type": "string"
                                            },
                                            "event_timestamp": {
                                                "Type": "bigint"
                                            },
                                            "event": {
                                                "Type": "struct<timestamp:string,flow_id:bigint,event_type:string,src_ip:string,src_port:int,dest_ip:string,dst_port:int,proto:string,app_proto:string,netflow:struct<pkts:int,bytes:bigint,start:string,finish:string,age:int,min_ttl:int,max_ttl:int>>"
                                            }
                                        }
                                    },
                                    "Format": {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.openx.data.jsonserde.JsonSerDe",
                                            "Parameters": {
                                                "paths": {
                                                    "Value": "availability_zone,event,event_timestamp,firewall_name"
                                                }
                                            }
                                        }
                                    }
                                },
                                "ses_send_events": {
                                    "Source": {
                                        "Link" : {
                                            "Tier": "mgmt",
                                            "Component": "baseline",
                                            "SubComponent": "opsdata",
                                            "Instance": "",
                                            "Version": "",
                                            "Type": "baselinedata"
                                        },
                                        "Prefix": "SES/SendEvent/"
                                    },
                                    "Layout": {
                                        "Columns": {
                                            "eventType": {
                                                "Type": "string"
                                            },
                                            "complaint": {
                                                "Type": "struct<arrivaldate:string,complainedrecipients:array<struct<emailaddress:string>>,complaintfeedbacktype:string,feedbackid:string,timestamp:string,useragent:string>"
                                            },
                                            "bounce": {
                                                "Type": "struct<bouncedrecipients:array<struct<action:string,diagnosticcode:string,emailaddress:string,status:string>>,bouncesubtype:string,bouncetype:string,feedbackid:string,reportingmta:string,timestamp:string>"
                                            },
                                            "mail": {
                                                "Type": "struct<timestamp:string,source:string,sourceArn:string,sendingAccountId:string,messageId:string,destination:string,headersTruncated:boolean,headers:array<struct<name:string,value:string>>,commonHeaders:struct<from:array<string>,to:array<string>,messageId:string,subject:string>,tags:struct<ses_configurationset:string,ses_source_ip:string,ses_outgoing_ip:string,ses_from_domain:string,ses_caller_identity:string>>"
                                            },
                                            "send": {
                                                "Type": "string"
                                            },
                                            "delivery": {
                                                "Type": "struct<processingtimemillis:int,recipients:array<string>,reportingmta:string,smtpresponse:string,timestamp:string>"
                                            },

                                            "open": {
                                                "Type": "struct<ipaddress:string,timestamp:string,userAgent:string>"
                                            },
                                            "reject": {
                                                "Type": "struct<reason:string>"
                                            },
                                            "click": {
                                                "Type": "struct<ipAddress:string,timestamp:string,userAgent:string,link:string>"
                                            }
                                        }
                                    },
                                    "Format" : {
                                        "Input": "org.apache.hadoop.mapred.TextInputFormat",
                                        "Output": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                                        "Serialisation": {
                                            "Library": "org.openx.data.jsonserde.JsonSerDe",
                                            "Parameters": {
                                                "mapping.ses_configurationset": {
                                                    "Value": "ses:configuration-set"
                                                },
                                                "mapping.ses_source_ip": {
                                                    "Value": "ses:source-ip"
                                                },
                                                "mapping.ses_from_domain": {
                                                    "Value": "ses:from-domain"
                                                },
                                                "mapping.ses_caller_identity": {
                                                    "Value": "ses:caller-identity"
                                                },
                                                "mapping.ses_outgoing_ip": {
                                                    "Value": "ses:outgoing-ip"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    /]
[/#macro]
