[#ftl]

[#-- TODO(rossmurr4y): feature: create the skeleton of a new infrastructure module for log consolidation --]
[#-- TODO(rossmurr4y): feature: add empty log consolidation module to the provider --]
[#-- TODO(rossmurr4y): feature: load skeleton structure blueprint --]
[#-- TODO(rossmurr4y): feature: add log consolidator s3 bucket to module blueprint --]
[#-- TODO(rossmurr4y): feature: add datafeed component to module blueprint  --]
[#-- TODO(rossmurr4y): feature: add log processor lambda function to module blueprint --]
[#-- TODO(rossmurr4y): feature: define placeholder log filter pattern --]
[#-- TODO(rossmurr4y): feature: define logging profile for forwarding logs to the log consolidation dest. bucket --]
[#-- TODO(rossmurr4y): feature: define deploymentProfile for opsdata -> log consolidation store replication --]
[#-- TODO(rossmurr4y): feature: define deploymentProfile to capture LB logs --]
[#-- TODO(rossmurr4y): feature: define deploymentProfile to capture ECS service/task logs --]
[#-- TODO(rossmurr4y): feature: define loggingprofile for use by apigw components to log to kinesis /w log processor function --]
[#-- TODO(rossmurr4y): feature: define deploymentProfile to apply new logging profile to apigw components --]
[#-- TODO(rossmurr4y): feature: add test case to the provider: log consolidation bucket exists --]
[#-- TODO(rossmurr4y): feature: add test case to the provider: opsdata replication rule exists --]
[#-- TODO(rossmurr4y): feature: add test case to the provider:  log processor exists --]
[#-- TODO(rossmurr4y): feature: add test case to the provider: datafeed exists and uses log processor --]
[#-- TODO(rossmurr4y): feature: add test case to the provider: mocked apigw exists and logs to a firehose --]
[#-- TODO(rossmurr4y): feature: add test case to the provider: mocked LB exists and has loadbalancerattributes enabling logs --]
[#-- TODO(rossmurr4y): feature: add test profile to module --]