[#ftl]
[@addResourceGroupInformation
    type=BACKUPSTORE_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_BACKUP_SERVICE,
            AWS_IDENTITY_SERVICE
        ]
/]

[@addResourceGroupInformation
    type=BACKUPSTORE_REGIME_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_BACKUP_SERVICE,
            AWS_IDENTITY_SERVICE
        ]
/]
