[#ftl]

[#assign AWS_ROUTE53RESOLVER_RESOLVER_LOGGING_RESOURCE = "resolverQueryLogging" ]
[@addServiceResource
    provider=AWS_PROVIDER
    service=AWS_ROUTE53RESOLVER_SERVICE
    resource=AWS_ROUTE53RESOLVER_RESOLVER_LOGGING_RESOURCE
/]

[#assign AWS_ROUTE53RESOLVER_RESOLVER_LOGGING_ASSOCIATION_RESOURCE = "resolverQueryLoggingAsccociation" ]
[@addServiceResource
    provider=AWS_PROVIDER
    service=AWS_ROUTE53RESOLVER_SERVICE
    resource=AWS_ROUTE53RESOLVER_RESOLVER_LOGGING_ASSOCIATION_RESOURCE
/]
