[#ftl]

[#assign AWS_RDS_CREATE_SNAPSHOT_TASK_TYPE = "aws_rds_create_snapshot" ]
[#assign AWS_ECS_SELECT_TASK_TASK_TYPE = "aws_ecs_select_task" ]
[#assign AWS_ECS_RUN_COMMAND_TASK_TYPE = "aws_ecs_run_command" ]
[#assign AWS_ECS_RUN_TASK_TASK_TYPE = "aws_ecs_run_task" ]
[#assign AWS_EC2_SELECT_INSTANCE_TASK_TYPE = "aws_ec2_select_instance" ]
[#assign AWS_KMS_ENCRYPT_VALUE_TASK_TYPE = "aws_kms_encrypt_value" ]
[#assign AWS_KMS_DECRYPT_CIPHERTEXT_TASK_TYPE = "aws_kms_decrypt_ciphertext" ]
[#assign AWS_LAMBDA_INVOKE_FUNCTION_TASK_TYPE = "aws_lambda_invoke_function"]
